on: workflow_dispatch

env:
  MEDIA_URL: https://nl22.seedr.cc/ff_get/894451831/falcon1.mkv?st=HHq5l01Gi-2-MlHrwYgeFQ&e=1618773804
jobs:
  get-media-info:
    name: Get Media Info
    runs-on: ubuntu-20.04

    steps:
      - run: |
          curl "$MEDIA_URL" --output media --no-progress-meter
          sudo apt-get update > /dev/null
          sudo apt-get install ffmpeg > /dev/null
          ffprobe -v quiet -print_format json -show_format -show_streams media
