on: workflow_dispatch

jobs:
  get-media-info:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: sudo chmod +x build-ffmpeg.sh && ./build-ffmpeg.sh
  
